
export const USER_STUDENT = 'student';
export const USER_COMPANY = 'company';

export const JOB_CAT = {
    FULLTIME : 'Full-Time Job',
    PARTTIME : 'Part-Time Job',
    INTERN : 'Internship',
    ONCAMPUS : 'On-Campus'    
}

export const APP_STATUS = {
    APP_STATUS_PENDING : 'pending',
    APP_STATUS_REVIEWED : 'reviewed',
    APP_STATUS_DECLINE : 'declined'
}

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_STUDENTS = 'GET_STUDENTS';
export const GET_OTHER_STUDENT_PROFILE = 'GET_OTHER_STUDENT_PROFILE';
export const GET_STUDENTS_ERR = 'GET_STUDENTS_ERR';

export const GET_STUDENT_PROFILE = 'GET_STUDENT_PROFILE';
export const GET_STUDENT_PROFILE_ERR = 'GET_STUDENT_PROFILE_ERR';

export const GET_COMPANY_PROFILE = 'GET_COMPANY_PROFILE';
export const GET_COMPANY_PROFILE_ERR = 'GET_COMPANY_PROFILE_ERR';

export const ERR_UPDATE_PROFILE = 'ERR_UPDATE_PROFILE';

export const UPDATE_STUDENT_EXP = 'UPDATE_STUDENT_EXP';
export const ADD_STUDENT_EXP = 'ADD_STUDENT_EXP';
export const DELETE_STUDENT_EXP = 'DELETE_STUDENT_EXP';

export const GET_STUDENT_EDUCATIONS = 'GET_STUDENT_EDUCATIONS';
export const ADD_STUDENT_EDUCATION = 'ADD_STUDENT_EDUCATION';
export const DELETE_STUDENT_EDUCATION = 'DELETE_STUDENT_EDUCATION';
export const UPDATE_STUDENT_EDUCATION = 'UPDATE_STUDENT_EDUCATION';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const CREATE_NEW_LOCAL_CONVERSATION = 'CREATE_NEW_LOCAL_CONVERSATION';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const GET_MESSAGES = 'GET_MESSAGES';
export const MESSAGE_ERR = 'MESSAGE_ERR';

export const GET_ALL_JOBS = 'GET_ALL_JOBS';
export const GET_ALL_JOBS_ERR = 'GET_ALL_JOBS_ERR';
export const APPLY_FOR_JOB = 'APPLY_FOR_JOB';
