export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_STUDENT_PROFILE = 'GET_STUDENT_PROFILE';
export const GET_STUDENT_PROFILE_ERR = 'GET_STUDENT_PROFILE_ERR';

export const GET_STUDENT_EDUCATIONS = 'GET_STUDENT_EDUCATIONS';
export const ADD_STUDENT_EDUCATION = 'ADD_STUDENT_EDUCATION';
export const DELETE_STUDENT_EDUCATION = 'DELETE_STUDENT_EDUCATION';
export const UPDATE_STUDENT_EDUCATION = 'UPDATE_STUDENT_EDUCATION';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
